<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Itmo.Dev.Platform.Postgres" Version="1.1.174" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Application\BankingSystem.Application.Abstractions\BankingSystem.Application.Abstractions.csproj" />
    </ItemGroup>

</Project>
